### ISSUE TITLE
[Feature Request]: allow configurable gas fee, rate options

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/celestia-da#29]
### Implementation ideas

We should be able to pass the gas fee, rate options from the client. This might need changes to the interface.

**Comment by musalbas** [comment]
Ideally there should just be a way to specify the gas price you want to pay, without needing to manually calculate the appropriate gas limit

Either celestia-node needs to implement a way to do this @Wondertan @renaynay

Or celestia-da needs to estimate the gas limit itself by called EstimateGas from celestia-core: https://github.com/celestiaorg/celestia-node/blob/main/state/core_access.go#L205

**Comment by musalbas** [comment]
This is rather high priority btw as I would only expect that spam / inscriptions could get worse or happen again
