### ISSUE TITLE
Unimplemented rpc error for MaxBlobSize

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/celestia-da#36]
```
something wrong rpc error: code = Unimplemented desc = unknown method MaxBlobSize for service da.DAService
10:12AM ERR DA layer submission failed error="unable to get DA max blob size" attempt=11 module=BlockManager
```

this is happening because celestia-da (main branch and last release) used go-da [57bc36006772](https://github.com/rollkit/celestia-da/blob/main/go.mod#L16) which does not have MaxBlobSize. 

we should update this to use `93600f2` which has the api MaxBlobSize.

**Comment by hoank101** [comment]
I have a PR , please review it -> https://github.com/rollkit/celestia-da/pull/40
